### PR TITLE
Add <~ overload to help with avoiding retain cycles

### PR DESCRIPTION
**Pull request by cassdeckard**
Description of the overload is found in comments above the code. I've
also provided a test that illustrates the problem it is attempting to
solve.

You could also come up with a new operator rather than overloading <~
but that might just make RxSugar look increasingly cryptic.

### CODE REVIEW

**Comment by cassdeckard** [comment]
Interested to know what you guys think of this. To me it feels a little nicer being able to do:
```
disposeBag ++ self <~ ClassOfSelf.someMethod <~ someObservable
```

rather than:
```
disposeBag ++ { [weak self] in self?.someMethod() } <~ someObservable
```

**Comment by marksands** [comment]
I'm personally not a fan of the `self <~ ClassType.method <~ observable` syntax to avoid retain cycles. I find a weak trampoline closure to be more concise in that situation and you don't sacrifice the readability or lose consistency with the `<~` operator.

Something like this:

```swift
func weakify<T: AnyObject>(_ owner: T, _ f: @escaping () -> Void) -> () -> () {
    return { [weak owner] in
        guard let _ = owner else { return }
        f()
    }
}

rxs.disposeBag ++ weakify(self, tableView.reloadData) <~ data.asObservable().toVoid()
```

(source: https://gist.github.com/klundberg/bf591578ff41f8ad33b3)

**Comment by JARinteractive** [comment]
+1 to @marksands. I wouldn't want to overload the meaning of the <~ operator. Either the weakify function or a weakify operator makes more sense to me. I lean towards preferring the function because it conveys meaning better than any operator I can think of at the moment.

Any opinions on whether some sort of weakify function belongs in RxSugar? It isn't solving a problem specific to Rx, but I do find myself needing to weakify things fairly often when using RxSugar

**Comment by cassdeckard** [comment]
I see what you mean about it not really being a problem specific to RxSugar. Maybe instead of including it in RxSugar, you could mention the issue and the workaround in the README.md?

**Comment by marksands** [comment]
I've been trying to revisit this but I'm not in love with any solution I've come up with.

I'm leaning toward something like this as part of the solution:

```swift
disposeBag ++ weakObserver(self, Class.foo) <~ observable
```

But my main issue is when I'm using anonymous closures, and there's no way that I know of to fix that issue:

```swift
disposeBag ++ { /* nothing we can do here to fix self */ } <~ observable
```

**Comment by JARinteractive** [comment]
```
disposeBag ++ weakObserver(self, { weakSelf, argument in /* ... */ }) <~ observable
```

**Comment by JARinteractive** [comment]
What operator would best communicate weak binding (must also be reversible, ie `~~>`)?
`<~~`
`<~?`
`<?~`

**Comment by marksands** [comment]
RE:

```
disposeBag ++ weakObserver(self, { weakSelf, argument in /* ... */ }) <~ observable
```

That could work, but I'll have to be convinced that this is an improvement. I do like that it better declares intent, and if a convention is established, then I'm more-or-less on board with _something_.

In my playground, I've been using `<~?` as an operator, so consider that my ➕ 1️⃣

**Pull request closed without merging**
